# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:             [jekyll-paginate,redcarpet,jekyll-gist,pygments.rb]


# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Phil Thomas
url:              http://pthoma.se
baseurl:          /

author:
  name:           'Phil Thomas'
  url:            http://pthoma.se

paginate:         5
paginate_path:    'blog/page:num'

# Custom vars

