# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate,jekyll-gist,kramdown,rouge]


# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Phil Thomas
url:              http://pthoma.se
baseurl:          /

author:
  name:           'Phil Thomas'
  url:            http://pthoma.se

paginate:         5
paginate_path:    'blog/page:num'

# Custom vars
# Default extension for new posts and pages
post_ext: markdown
page_ext: html
